name: PR Check

on:
  pull_request:
    branches: [develop]
    types: [opened, edited, reopened, synchronize]

jobs:
  issues:
    uses: NoorDigitalAgency/.github/.github/workflows/check-linked-issues.yaml@main
    secrets: inherit

  test:
    uses: ./.github/workflows/test-job.yaml # TODO: Check to match the correct file name
    with:
      stage: alpha
    secrets: inherit

  build:
    uses: ./.github/workflows/build-job.yaml # TODO: Check to match the correct file name
    with:
      stage: alpha
    secrets: inherit

  reviewers:
    needs: [test,build]
    uses: NoorDigitalAgency/.github/.github/workflows/assign-reviewers.yaml@main
    with:
      strict: false # TODO: Set to true if reviews are mandetory
