name: Re-deploy
on:
  workflow_call:
    inputs:
      version:
        description: Deployment Version
        type: string
        required: true
      resource_type:
        description: Kubernetes Resource Type
        type: string
        default: daemonset
        required: false
      resource_namespace:
        description: Kubernetes Resource Namespace
        type: string
        default: noor
        required: false
      kubectl_version:
        description: Kubectl Version
        type: string
        default: v1.21.11
        required: false
      stage:
        description: Stage
        type: string
        required: true
      deploy_to_kubernetes:
        description: If the image should be deployed to Kubernetes
        type: boolean
        required: false
        default: true

jobs:
  deploy:
    environment: ${{ inputs.stage }}
    runs-on: ubuntu-latest
    name: Re-deploy
    steps:
      - id: analyzing
        name: Analyzing
        uses: actions/github-script@v6
        with:
          script: |
            const version = '${{ inputs.version }}';
            const stage = '${{ inputs.stage }}';
            const resource = '${{ inputs.resource_type }}';
            const name = context.payload.repository.name;
            const label = stage !== 'production' ? `-${ stage }` : '';
            return {
              version: `noorteam/${ name }:${ version }`,
              latest: `noorteam/${ name }:latest${ label }`,
              resource: `${ resource }/${ name }${ label }`
            };

      - name: Docker Hub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: |
          docker pull ${{ fromJson(steps.analyzing.outputs.result).version }}
          docker tag ${{ fromJson(steps.analyzing.outputs.result).version }} ${{ fromJson(steps.analyzing.outputs.result).latest }}
          docker push ${{ fromJson(steps.analyzing.outputs.result).latest }}

      - env:
          OPENVPN_CONFIG: ${{ secrets.OPENVPN_CONFIG }}
          OPENVPN_USERNAME: ${{ secrets.OPENVPN_USERNAME }}
          OPENVPN_PASSWORD: ${{ secrets.OPENVPN_PASSWORD }}
        run: |
          [[ ! -z "$OPENVPN_CONFIG" ]] && [[ ! -z "$OPENVPN_USERNAME" ]] && [[ ! -z "$OPENVPN_PASSWORD" ]] && \
          sudo apt install apt-transport-https && wget https://swupdate.openvpn.net/repos/openvpn-repo-pkg-key.pub && sudo apt-key add openvpn-repo-pkg-key.pub && \
          sudo wget -O /etc/apt/sources.list.d/openvpn3.list "https://swupdate.openvpn.net/community/openvpn3/repos/openvpn3-$(lsb_release -c -s).list" && \
          sudo apt update && sudo apt install openvpn3 && echo "$OPENVPN_CONFIG" > config.ovpn && echo "$OPENVPN_USERNAME" > config.login && echo "$OPENVPN_PASSWORD" >> config.login && \
          openvpn3 session-start --config config.ovpn && echo "TUNNEL_CONNECTION=established" >> $GITHUB_ENV || echo

      - if: inputs.deploy_to_kubernetes == true
        name: Kubernetes Resource Update
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        run: |
          mkdir -p ~/.kube
          echo "$KUBE_CONFIG" > ~/.kube/config
          curl -LO https://dl.k8s.io/release/${{ inputs.kubectl_version }}/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          ./kubectl rollout restart ${{ fromJson(steps.analyzing.outputs.result).resource }} --namespace=${{ inputs.resource_namespace }}

      - if: ${{ always() }}
        run: echo && [ '${{ env.TUNNEL_CONNECTION }}' == 'established' ] && openvpn3 session-manage --disconnect --config config.ovpn || echo
